[package]
name = "goscript-vm"
version = "0.1.0"
authors = ["oxfeeefeee <pb01005051@gmail.com>"]
edition = "2018"

[dependencies]
slotmap = "0.4"
ordered-float = "2.0"
time-test = "0.2.2"

[dependencies.goscript-parser]
path = "../parser"
version = "0.1.0"
