[package]
name = "goscript-types"
version = "0.1.0"
authors = ["oxfeeefeee <pb01005051@gmail.com>"]
edition = "2018"

[dependencies]
slotmap = "0.4"
num-bigint = "0.2.6"
num-rational = "0.2.4"
num-traits = "0.2"

[dependencies.goscript-parser]
path = "../parser"
version = "0.1.0"